kind: pipeline
name: default

steps:
- name: build
  image: golang
  environment:
    CGO_ENABLED: 0
  commands:
    - go get github.com/Sirupsen/logrus
    - go get github.com/urfave/cli
    - go test -cover -coverprofile=coverage.out
    - go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a

- name: docker-image
  image: plugins/docker
  settings:
    repo: sybex/drone-clair
    tags:
      - latest
      - 0.${DRONE_BUILD_NUMBER}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

